CREATE DATABASE SPTest COLLATE Cyrillic_General_CI_AS;
GO

USE SPTest;

CREATE TABLE PRODUCT(
	ID_PRODUCT 	INT IDENTITY(1,1) NOT NULL, 
	NAME 		VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_PRODUCT)
);

CREATE TABLE PHARMACY(
	ID_PHARMACY INT IDENTITY(1,1) NOT NULL, 
	NAME 		VARCHAR(255) NOT NULL,
	ADDRESS 	VARCHAR(255) NOT NULL,
	PHONE       VARCHAR(25) NOT NULL,
	PRIMARY KEY (ID_PHARMACY)
);

CREATE TABLE STOCK(
	ID_STOCK    INT IDENTITY(1,1) NOT NULL, 
	ID_PHARMACY INT NOT NULL,
	NAME 		VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID_STOCK),
	FOREIGN KEY (ID_PHARMACY) REFERENCES PHARMACY(ID_PHARMACY)
);

CREATE TABLE PART(
	ID_PART     INT IDENTITY(1,1) NOT NULL, 
	ID_PRODUCT  INT NOT NULL,
	ID_STOCK    INT NOT NULL,
	QUANTITY    INT NOT NULL,
	PRIMARY KEY (ID_PART),
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	FOREIGN KEY (ID_STOCK) REFERENCES STOCK(ID_STOCK)
);
GO

--INSERT INTO PRODUCT (NAME) VALUES ('Товар 1');
--INSERT INTO PHARMACY (NAME, ADDRESS, PHONE) VALUES ('Аптека 1', 'г. Новороссийск', '7-978-125-16-11');
--INSERT INTO STOCK (ID_PHARMACY, NAME) VALUES (1, 'Склад 1');
--INSERT INTO PART (ID_PRODUCT, ID_STOCK, QUANTITY) VALUES (1,1,1);
